### ISSUE TITLE
delay时间用Int很难受

### ISSUE THREAD

**Issue by winddpan** [WangWenzhuang/ZKProgressHUD#1]
改成Float是否好些。
ZKProgressHUDConfig没有public，无法全局设置样式。
背景能提供可选BlurView的3个样式？

**Comment by WangWenzhuang** [comment]
@winddpan @winddpan 你好，感谢你的反馈，鉴于你提的问题

1. delay 和设置全局自动移除已经改成 Double 类型（内部使用微秒实现），可以使用小数，不会影响以前的代码。
2. ZKProgressHUDConfig中的配置在 ZKProgressHUD的类方法中都可以设置，详情请看[自定义显示样式](https://github.com/WangWenzhuang/ZKProgressHUD#自定义显示样式)
3. HUD的背景添加了setEffectStyle、setEffectAlpha方法，用于设置毛玻璃效果，不过会和背景色互斥，具体的互斥规则请看[设置 HUD 毛玻璃效果](https://github.com/WangWenzhuang/ZKProgressHUD#设置-hud-背景色与-effectstyle-互斥如果设置背景色effectstyle--none默认值uicolorred-0--2550-green-0--2550-blue-0--2550-alpha-08)

在新版本 1.5 中都已经实现！！！
再次感谢你的反馈，有任何问题可以随时联系我😊
