### ISSUE TITLE
怎么在显示的消息消失后开始执行函数

### ISSUE THREAD

**Issue by isxq** [WangWenzhuang/ZKProgressHUD#2]
**控件隐藏后的回掉该怎么执行**
之前的版本有一个方法可以在当前显示消息结束后执行函数块，这个版本去掉了这个功能了吗？如果我要实现那种效果该怎么做？

**Comment by WangWenzhuang** [comment]
@NovemberTri 你好，可以跟我详细说一下你的需求么？可以加我的 QQ 1020304029 联系上我。

**Comment by WangWenzhuang** [comment]
@NovemberTri 已经更新至2.0，你看一下是否符合你的需求
