### ISSUE TITLE
Fix for Swift 4

### ISSUE THREAD

**Issue by bpolat** [WangWenzhuang/ZKProgressHUD#3]
Please replace the line in String-Extension.swift file with new Swift syntax.

        let attribute = [ NSFontAttributeName: font ]

**Comment by WangWenzhuang** [comment]
Thanks for your feedback，the following is my comments:
"let attribute = [ NSFontAttributeName: font ]" is the syntax of  Swift 3.2 version，
But for Swift 4.0,  should be "let attribute = [ NSAttributedStringKey.font: font ]".
If you are using Swift3.2, Please following my release 1.5 version. e.g:
pod 'ZKProgressHUD', '1.5'

**Comment by WangWenzhuang** [comment]
@bpolat 
Thanks for your feedback，the following is my comments:
"let attribute = [ NSFontAttributeName: font ]" is the syntax of Swift 3.2 version，
But for Swift 4.0, should be "let attribute = [ NSAttributedStringKey.font: font ]".
If you are using Swift3.2, Please following my release 1.5 version. e.g:
pod 'ZKProgressHUD', '1.5'
