### ISSUE TITLE
xcode10 集成到项目里报错

### ISSUE THREAD

**Issue by grx123** [WangWenzhuang/ZKProgressHUD#4]
![2018-10-10 2 22 04](https://user-images.githubusercontent.com/10874922/46716886-4cc6ea80-cc98-11e8-90f8-22cb64a08735.png)
![2018-10-10 2 21 54](https://user-images.githubusercontent.com/10874922/46716901-56505280-cc98-11e8-9651-0e4777f2e116.png)
![2018-10-10 2 21 40](https://user-images.githubusercontent.com/10874922/46716903-594b4300-cc98-11e8-80a9-511102306d21.png)

**Comment by WangWenzhuang** [comment]
感谢使用，请确认你的项目的 Swift 版本

如果使用 Swift 4.2 请使用最新版3.2
pod 'ZKProgressHUD', '3.2'

如果使用 Swift 4.0 请使用3.1版本
pod 'ZKProgressHUD', '3.1'

如果使用 Swift 3.2 请使用1.5版本
pod 'ZKProgressHUD', '1.5'
