### ISSUE TITLE
Loader is showing multiple times

### ISSUE THREAD

**Issue by prithiviraj** [WangWenzhuang/ZKProgressHUD#7]
I'm calling the below multiples time, it's showing multiple loaders.

My question is if the loader is already showing, even if I call the show loader, it should not show.

here we don't have a delegate to check if the loader is already showing.

ZKProgressHUD.show()

**Comment by WangWenzhuang** [comment]
pod 'ZKProgressHUD', '5.1'
`ZKProgressHUD.isShowing`
