### ISSUE TITLE
可以增加hud的superView的选择吗？

### ISSUE THREAD

**Issue by DreamParagon** [WangWenzhuang/ZKProgressHUD#8]
作者您好，我想问下，后续更新可以增加hud的superView的选择吗？因为现在是写死的加载在window上，这样如果网络太慢，用户无法选择点到别的页面上去。。。。希望能增加这方面的选择

**Comment by WangWenzhuang** [comment]
ZKProgressHUD.show(maskStyle: .hide)遮罩样式修改为hide，在show()时遮罩将隐藏，此时用户是可以点击的，这样可以解决你的问题么？ @DreamParagon

**Comment by DreamParagon** [comment]
😁可以的，只是我想最好能够有遮罩，但是把导航栏和tabbar露出来~我先隐藏下吧
